services:
  - type: web
    name: cloudflow-s3-uploader
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AWS_BUCKET
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
